services:
  flask:
    image: aura-map:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    env_file:
      - .env.dev
    environment:
      APP_VERSION: "1.1.0"
      DB_HOST: postgres
      DB_DATABASE: auradb
      DB_USER: aurauser
    networks:
      - public
      - private
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: aurauser
      POSTGRES_DB: auradb
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aurauser -d auradb"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  public:
    driver: bridge
  private:
    internal: true

volumes:
  postgres-data:

secrets:
  pg_password:
    file: ./secrets/pg_password.txt
